---
#
# This playbook is for site-local customization to ElastiCluster's
# playbooks.  It runs *before* any other playbook distributed with
# ElastiCluster has gotten its chance to run (including the "common setup").
#
# An empty playbook is checked into the Git repository.  If you make
# any local modifications, please run `git update-index
# --assume-unchanged after.yml` to avoid committing them accidentally
# into ElastiCluster's main branch.
#
- name: Apply local customizations (before)
  tags:
    - before
    - local
  hosts: slurm_master
  roles: []
  tasks: 
    - name: Ensure groups exists
      ansible.builtin.group:
        name: '{{item}}'
        state: present
      loop: '{{customer_groups}}'
      when: 'item is defined'

    - name: Add initial users to the cluster
      ansible.builtin.user:
        name: '{{item.name}}'
        shell: /bin/bash
        groups: '{{item.groups | default([""]) | from_yaml | join(",") }}'
        append: yes
      loop: '{{customer_users | from_yaml}}'
      when: 'item is defined'
    
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: '{{item.name}}'
        state: present
        key: https://github.com/{{item.github_username}}.keys
      loop: '{{customer_users | from_yaml}}'
      when: 'item is defined'