---

- name: install NFS client software (Debian/Ubuntu)
  tags:
    - nfs
    - nfs-client
  package:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: '{{pkg_install_state}}'
  when: is_debian_compatible

- name: install NFS client software (RHEL-compatible)
  tags:
    - nfs
    - nfs-client
  package:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: '{{pkg_install_state}}'
  when: is_rhel_compatible


- name: Ensure `rpcbind` is running (Debian)
  ansible.builtin.service:
    name: rpcbind
    enabled: yes
    state: started
  when: is_debian

- name: Ensure `rpcbind` is running (RHEL-compatible)
  ansible.builtin.service:
    name: rpcbind
    enabled: yes
    state: started
  when: is_rhel_compatible

- name: Ensure `portmap` is running (Ubuntu prior to 14.04)
  ansible.builtin.service:
    name: portmap
    enabled: yes
    state: started
  when: is_ubuntu and not is_ubuntu_14_04_or_later

- name: Ensure `rpcbind` is running (Ubuntu 14.04 or newer)
  ansible.builtin.service:
    name: rpcbind
    enabled: yes
    state: started
  when: is_ubuntu_14_04_or_later


- name: Mount NFS filesystems
  tags:
    - nfs
    - nfs-client
  include_tasks: nfsmount.yml
  vars:
    fs: '{{item}}'
  loop: '{{NFS_MOUNTS}}'
