---

- name: Umount bucket first to avoid "Stale file handle" error
  ansible.posix.mount:
    path: '{{ fs.mountpoint }}'
    state: "unmounted"
  when: 'fs.is_bucket == true'

- name: ensure {{fs.mountpoint}} directory exists
  ansible.builtin.file:
    path: "{{fs.mountpoint}}"
    state: directory

- name: add to /etc/fstab
  ansible.posix.mount:
    path: '{{ fs.mountpoint }}'
    src: "{{ fs.fs }}"
    fstype: nfs
    opts: '{{ fs.options|default("rw,async") }}'
    state: "{{ fs.state|default('mounted') }}"


- name: Allow NFS homes through SELinux
  command: |
    setsebool -P use_nfs_home_dirs=1
  when: 'fs.mountpoint == "/home" and is_rhel_compatible and ansible_selinux.status == "enabled"'
