---

- name: Defining a name for the credential file
  ansible.builtin.set_fact:
    credential_file: "/etc/passwd-s3fs.{{ service.hostname }}"
    

- name: Deploy s3fs credential file
  vars:
    ACCESS_KEY_ID: '{{ service.access_key_id }}'
    ACCESS_SECRET_KEY: '{{ service.access_secret_key }}'
  ansible.builtin.template:
    src: "etc/passwd-s3fs.j2"
    dest: "{{ credential_file }}"
    owner: root
    group: root
    mode: '0600'
  

- name: Mount new volumes and create fstab entries
  ansible.posix.mount: 
    path: "{{ bucket_item.mountpoint }}"
    src: "{{ bucket_item.name }}"
    fstype: "fuse.s3fs"
    opts: "{{ bucket_item.options | default('allow_other,use_path_request_style', true) }},passwd_file={{ credential_file }},url={{ service.url }}"
    state: "mounted"
  loop: "{{ service.buckets }}"
  loop_control:
    loop_var: bucket_item

