---

- name: Defining a name for the credential file
  ansible.builtin.set_stats:
    data:
      credential_file: "~/.passwd-s3fs.{{ service.hostname }}"
    aggregate: no
    per_host: no


- name: Deploy s3fs credential file
  vars:
    ACCESS_KEY_ID: '{{ service.access_key_id }}'
    ACCESS_SECRET_KEY: '{{ service.access_secret_key }}'
  ansible.builtin.template:
    src: "passwd-s3fs.j2"
    dest: "{{ credential_file }}"
    owner: root
    group: root
    mode: 0600


- name: Mount new volumes and create fstab entries
  ansible.posix.mount: 
    path: "{{ item.mountpoint }}"
    src: "{{ item.name }}"
    fstype: "fuse.s3fs"
    opts: "{{ item.options | default('allow_other,use_path_request_style', true) }},passwd_file={{ credential_file }},url={{ item.url }}"
    state: "mounted"
  loop: "{{ service.buckets }}"

