---
#
# Install all "standard" software that could be needed for installing
# other software, and for effectively managing a cluster.  Basically
# this includes the following categories of utilities:
#
# - compression utilities and archivers
# - version control systems
# - standard UNIX build utilities like C compiler, make, etc.
# - a few other misc utilities that one can reasonably expect
#

- name: Install commonly needed software (RHEL-family)
  package:
    name:
      # compression and archivers
      - bzip2
      - cpio
      - gzip
      - lzip
      - p7zip
      - tar
      - unzip
      - xz
      - zip
      # version control systems
      - git
      # basic build environment
      - gcc
      - gcc-c++
      - gcc-gfortran
      - glibc-devel
      - make
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - xz-devel 
      # other "standard" utilities
      - bash-completion
      - kexec-tools
      - m4
      - rsync
      - screen
      - tmux
      - vim
      - htop
      - netcat
    state: '{{ pkg_install_state }}'
